models:
  music2vec:
    window_size: 5
    negative_sample: 20
    down_sample: 1e-3
    learning_rate: 0.025
    epochs: 5
    vector_dim: 300
session:
  interval: 60
algorithms:
  m2vTN: True
  sm2vTN: True
  csm2vTN: True
  csm2vUK: True
evaluation:
  dataset: 'new'
  cross-validation: 5
  k: 5
  topN: 5
  metrics: ['precision', 'recall', 'hitrate', 'f1']
logfile: 'output_new.log'
num_parallel: 5
embeddings:
  glove: 
    usage: False
    path: 'm2v_glove'
  music2vec: 
    usage: True
    path: 'music2vec'
  doc2vec: 
    usage: False
    path: 'doc2vec'
  rnn: 
    usage: False
    path: ''
