models:
  music2vec:
    window_size: 5
    negative_sample: 20
    down_sample: 1e-3
    learning_rate: 0.025
    epochs: 5
    vector_dim: 300
  doc2vec:
    window_size: 5
    negative_sample: 20
    down_sample: 1e-3
    learning_rate: 0.025
    epochs: 5
    vector_dim: 300
  glove:
    window_size: 5
    vector_dim: 300
    learning_rate: 0.025
    epochs: 5
  seq2seq:
    vector_dim: 100
    batch_size: 32
    epochs: 50
    model: 'GRU'
    window_size: 5
session:
  interval: 60
evaluation:
  dataset: 'xiami'
  cross-validation: 5
  k: 5
  topN: 5
logfile: 'outputs/output_xiami.log'
embeddings-only: False
embeddings:
  music2vec: 
    usage: True
    path: 'music2vec'
  doc2vec: 
    usage: False
    path: 'doc2vec'
  glove: 
    usage: False
    path: 'glove'
  seq2seq: 
    usage: False
    path: 'embeddings_seq2seq'
