models:
  music2vec:
    window_size: 5
    negative_sample: 20
    down_sample: 1e-3
    learning_rate: 0.025
    epochs: 5
    vector_dim: 300
session:
  interval: 60
evaluation:
  dataset: 'xiami-small'
  cross-validation: 5
  k: 5
  topN: 5
logfile: 'outputs/output_xiami-small.log'
embeddings:
  music2vec: 
    usage: True
    path: 'music2vec'
  doc2vec: 
    usage: False
    path: 'doc2vec'
  glove: 
    usage: False
    path: 'm2v_glove'
  rnn: 
    usage: False
    path: 'embeddings1_listening-id#1.csv'
    session_path: 'embeddings1_session-id#1.csv'
