models:
  rnn:
    embedding_dim: [256]
    batch: 512
    epochs: [100]
    model: ['LSTM']
    window: [5]
    bi: [False]
    num_units: [512]
  music2vec:
    window: [5]
    epochs: [5]
    down_sample: [1e-3]
    learning_rate: [0.025]
    embedding_dim: [300]
    negative_sample: [20]
  doc2vec:
    window: [10]
    epochs: [10]
    down_sample: [1e-4]
    learning_rate: [0.025]
    embedding_dim: [50]
    negative_sample: [10]
  glove:
    window: [10]
    embedding_dim: [100]
    epochs: [15]
    learning_rate: [0.025]
session:
  interval: 60
evaluation:
  dataset: 'xiami'
  cross-validation: 5
  k: 5
  topN: 5
results:
  summarized: 'outputs/results_summarized_xiami.csv'
  full: 'outputs/results_full_xiami.csv'
embeddings:
  music2vec: 
    usage: False
  doc2vec: 
    usage: False
  glove: 
    usage: False
  rnn: 
    usage: True
