models:
  music2vec:
    window_size: [20]
    vector_dim: [50]
    learning_rate: [0.015]
    epochs: [10]
    down_sample: [1e-4]
    negative_sample: [10]
  doc2vec:
    window_size: [20]
    vector_dim: [50]
    learning_rate: [0.035]
    epochs: [10]
    down_sample: [1e-4]
    negative_sample: [10]
  glove:
    window_size: [10]
    vector_dim: [100]
    learning_rate: [0.025]
    epochs: [15]
session:
  interval: 60
evaluation:
  dataset: 'music2all'
  cross-validation: 5
  k: 5
  topN: 5
logfile: 'outputs/music2all.log'
embeddings-opt: True
embeddings:
  music2vec: 
    usage: True
    path: 'music2vec'
  doc2vec: 
    usage: True
    path: 'doc2vec'
  glove: 
    usage: False
    path: 'glove'
  seq2seq: 
    usage: False
    path: 'seq2seq'
